---
# tasks file for apt-packages
- name: Install `apt` packages
  become: true
  ansible.builtin.apt:
    pkg:
      - net-tools
      - nano
      - parted
      - cockpit
      - unzip
      - git
    state: present
    update_cache: false
