---
roles:
  - name: nerd-fonts
    src: https://github.com/fmarcelinoPT/ansible-role-nerd-fonts.git
    version: main
    scm: git
  - name: terraform
    src: https://github.com/fmarcelinoPT/ansible-role-terraform.git
    version: master
    scm: git
  - name: docker
    src: https://github.com/fmarcelinoPT/ansible-role-docker.git
    version: master
    scm: git
