all:
  vars:
    # A list of users who will be added to the docker group.
    docker_users: [donutuse]
    # Action for Oh My Zsh
    ohmyzsh_action: "install"
    # Roles to be applied to all hosts
    global_roles:
      #- hello
      - sys-apt-upgrade
      - apt-packages
      - ohmyzsh
      - nerd-fonts
      - hosts_hypervisors
  children:
    hypervisors:
      vars:
        install_certificates: true
      hosts:
        # Hypervisors
        hera.onemarc.io:
          ansible_ssh_user: ansiblebot
          ansible_ssh_private_key_file: ~/.ssh/support_rsa
          ansible_roles:
            - certs_hypervisor        # We will take advantage of the replication features of Proxmox
            - pve_restart_pveproxy    # Need to restart pveproxy after copying certificates `certs_hypervisor` if `install_certificates = true`
        kronos.onemarc.io:
          ansible_ssh_user: ansiblebot
          ansible_ssh_private_key_file: ~/.ssh/support_rsa
          ansible_roles:
            - pve_restart_pveproxy    # Need to restart pveproxy after copying certificates `certs_hypervisor` if `install_certificates = true`
        poseidon.onemarc.io:
          ansible_ssh_user: ansiblebot
          ansible_ssh_private_key_file: ~/.ssh/support_rsa
          ansible_roles:
            - pve_restart_pveproxy    # Need to restart pveproxy after copying certificates `certs_hypervisor` if `install_certificates = true`
        zeus.onemarc.io:
          ansible_ssh_user: ansiblebot
          ansible_ssh_private_key_file: ~/.ssh/support_rsa
          ansible_roles:
            - pve_restart_pveproxy    # Need to restart pveproxy after copying certificates `certs_hypervisor` if `install_certificates = true`
