all:
  vars:
    # A list of users who will be added to the docker group.
    docker_users: [donutuse]
    # Action for Oh My Zsh
    ohmyzsh_action: "install"
    # Roles to be applied to all hosts
    global_roles:
      - sys-apt-upgrade
      - apt-packages
      - ohmyzsh
      - nerd-fonts
  children:
    ungrouped:
      hosts:
        192.168.8.10:
          ansible_ssh_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/support_rsa
          ansible_roles:
            - pihole
