all:
  vars:
    # A list of users who will be added to the docker group.
    docker_users: [ fmarcelino ]
    # Roles to be applied to all hosts
    global_roles:
      # - hello
      - sys-apt-upgrade
      - apt-packages
      - omzh
      - nerd-fonts
  children:
    ungrouped:
      # vars:
      #   DOMAIN: onemarc.io
      hosts:
        localhost:
          ansible_connection: local
          ansible_roles:
            # - snapd-packages
            - apt-packages-desktop
            - snapd-packages-desktop
            - meld
            - terraform
            - docker
