all:
  vars:
    global_roles:
#      - hello
#      - sys-apt-upgrade
      - apt-packages
      - omzh
      - nerd-fonts
  children:
    ungrouped:
      #      vars:
      #        DOMAIN: onemarc.io
      hosts:
        localhost:
          ansible_connection: local
          ansible_roles:
            - apt-packages-desktop
#            - snapd-packages
            - snapd-packages-desktop
            - meld

