all:
  vars:
    # A list of users who will be added to the docker group.
    docker_users: [fmarcelino]
    # Action for Oh My Zsh
    ohmyzsh_action: "install"
    # Roles to be applied to all hosts
    global_roles:
      - hello
      #- sys-apt-upgrade
      #- apt-packages
      - ohmyzsh
      #- nerd-fonts
  children:
    ungrouped:
      vars:
        #   DOMAIN: onemarc.io
        rider_action: "uninstall"
      hosts:
        #192.168.8.111:
        #  ansible_ssh_user: ubuntu
        #  ansible_ssh_private_key_file: ~/.ssh/id_rsa_proxmox_template
        localhost:
          ansible_connection: local
          ansible_roles:
            #- snapd-packages
            #- apt-packages-desktop
            #- snapd-packages-desktop
            #- meld
            #- terraform
            #- docker
            - jetbrains-rider
