- name: Install dependencies
  ansible.builtin.apt:
    name:
      - wget
      - gpg
    state: present
    update_cache: yes
  become: true

# Synology Drive

- name: Install Synology Drive
  block:

    - name: Enable COPR repository for Synology Drive
      ansible.builtin.command:
        cmd: dnf copr enable emixampp/synology-drive -y
      args:
        creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:emixampp:synology-drive.repo
      become: true

    - name: Install Synology Drive (GNOME)
      ansible.builtin.dnf:
        name: synology-drive
        state: present
        update_cache: yes
      become: true

# NVidia drivers

- name: Install NVidia drivers
  block:

    - name: Download NVIDIA keyring package
      ansible.builtin.get_url:
        url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb"
        dest: "/tmp/cuda-keyring_1.1-1_all.deb"
        mode: '0644'
      become: true

    - name: Install NVIDIA keyring package
      ansible.builtin.apt:
        deb: "/tmp/cuda-keyring_1.1-1_all.deb"
      become: true

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      become: true

    - name: Install NVIDIA driver
      ansible.builtin.apt:
        name: "nvidia-open-570"
        state: present
      become: true

# Microsoft applications installation

- name: Install VSCode
  block:
    - name: Add Microsoft GPG key
      ansible.builtin.shell: |
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /usr/share/keyrings/packages.microsoft.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/packages.microsoft.gpg
      become: true

    - name: Add VSCode repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
        state: present
      become: true

    - name: Install VSCode
      ansible.builtin.apt:
        name: code
        update_cache: yes
      become: true

- name: Install Microsoft Edge
  block:
    - name: Add Microsoft GPG key
      ansible.builtin.shell: |
        wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /usr/share/keyrings/packages.microsoft.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/packages.microsoft.gpg
      become: true

    - name: Add Microsoft Edge repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/edge stable main"
        state: present
      become: true

    - name: Install Microsoft Edge
      ansible.builtin.apt:
        name: microsoft-edge-beta
        update_cache: yes
      become: true

# Installation of snap applications

- name: Install Obsidian
  block:
    - name: Install Obsidian (classic)
      become: true
      community.general.snap:
        name:
          - obsidian
        state: present
        classic: true

- name: Install Draw.io
  block:
    - name: Install Draw.io (snap)
      become: true
      community.general.snap:
        name:
          - drawio
        state: present

- name: Install Spotify
  block:
    - name: Install Spotify (snap)
      become: true
      community.general.snap:
        name:
          - spotify
        state: present

- name: Install krita
  block:
    - name: Install krita (snap)
      become: true
      community.general.snap:
        name:
          - krita
        state: present

- name: Update target desktop shortcuts
  block:
    - name: Copy .desktop files to /usr/share/applications/
      become: true
      ansible.builtin.shell: cp /var/lib/snapd/desktop/applications/*.desktop /usr/share/applications/
