---
# tasks file for apt-packages-desktop
- name: Install `apt` packages 4 Desktop
  become: true
  ansible.builtin.apt:
    pkg:
      - snapd
      - yakuake
      - keepassxc
      - filezilla
      - krita
      - remmina
      - network-manager-fortisslvpn
      - network-manager-openvpn
    state: present
    update_cache: false