---
# tasks file for snapd-packages-desktop
- name: Install `snapd-packages` 4 Desktop
  community.general.snap:
    name:
      - obsidian
      - code
      - drawio
#      - bar
#    options:
#      - com=A
#      - foo:fooPar=X
#      - bar:barPar=Y