---
# Ensure support tools is installed
- name: Install `apt` packages (Debian/Ubuntu)
  become: true
  ansible.builtin.apt:
    pkg:
      - git
    state: present
    update_cache: false
  when: ansible_facts['pkg_mgr'] == 'apt'

- name: Install `dnf` packages (RHEL/CentOS/Fedora)
  become: true
  ansible.builtin.dnf:
    name:
      - git
    state: present
  when: ansible_facts['pkg_mgr'] == 'dnf'

# Install git-credential-manager
# Resources: https://github.com/git-ecosystem/git-credential-manager

- name: Install and configure 'git-credential-manager'
  ansible.builtin.shell: |
    dotnet tool install -g git-credential-manager
    git-credential-manager configure

- name: Setup git username and email
  ansible.builtin.shell: |
    git config --global user.name "Filipe Marcelino"
    git config --global user.email fmarcelino@gmail.com